etcd_cluster_type: 'new'

## Deploy Etcd Cluster Host list
## ********************************************************************************************************************************
k8s_master_ip_list: >-
  [{% for host in groups['kube-master'] -%}
    '{{ host }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

etcd_master_ip_str: >-
  {% for host in groups['etcd'] -%}
    {{ host }}
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}

etcd_master_ip_list: >-
  [{% for host in groups['kube-master'] -%}
    '{{ host }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

etcd_initial_cluster_addr: >-
  {% for host in groups['etcd'] -%}
    {{ etcd_peer_url_scheme }}://
    {%- if etcd_interface != "" -%}
      {{ hostvars[host]['ansible_' + etcd_interface].ipv4.address }}
    {%- else -%}
      {{ hostvars[host].ansible_default_ipv4.address }}
    {%- endif -%}
  :{{ etcd_client_port }}
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}

etcd_master_default_ip_str: >-
  {% for host in groups['etcd'] -%}
    {{ hostvars[host].ansible_default_ipv4.address }}
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}

etcd_master_one_host: "{{ groups['etcd'][0] }}"