## CRI-TOOLS
## ********************************************************************************************************************************

# https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md
# https://github.com/kubernetes-sigs/cri-tools/releases
cri_tools_version: v1.20.0