---
## Kubernetes
## ********************************************************************************************************************************
## Permissions
# - name: Move location Kubelet.conf in Crane Home
#   shell: >
#     find {{ kubernetes_etc_dirs }} | xargs -i chown {{ ssh_connect_user }} {}
#   ignore_errors: true

- name: Copy Master CA Files.
  shell: "scp -r -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no \
            -i {{ ssh_public_key }} \
            -P {{ ssh_connect_port }} \
            {{ kubernetes_pki_dirs }}{{ item[1] }} \
            {{ ssh_connect_user }}@{{ item[0] }}:{{ kubernetes_pki_dirs }}{{ item[1] }}"
  with_nested:
    - "{{ add_master_ip_list }}"
    - ['apiserver-key.pem', 'apiserver.pem', 'ca-key.pem', 'ca.pem', 'front-proxy-ca-key.pem', 'front-proxy-ca.pem', 'front-proxy-client-key.pem', 'front-proxy-client.pem', 'sa.key', 'sa.pub']

- name: Copy Cluster Config Files.
  shell: "scp -r -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no \
            -i {{ ssh_public_key }} \
            -P {{ ssh_connect_port }} \
            {{ kubernetes_etc_dirs }}{{ item[1] }} \
            {{ ssh_connect_user }}@{{ item[0] }}:{{ kubernetes_etc_dirs }}{{ item[1] }}"
  with_nested:
    - "{{ add_master_ip_list }}"
    - ['admin.conf', 'bootstrap-kubelet.conf', 'controller-manager.conf', 'scheduler.conf']

## Etcd
## ********************************************************************************************************************************

- name: Copy Etcd CA Files in Nodes
  shell: "scp -r -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -i {{ ssh_public_key }} \
            -P {{ ssh_connect_port }} {{ etcd_ssl_dirs }}{{ item[1] }}  {{ ssh_connect_user }}@{{ item[0] }}:{{ etcd_ssl_dirs }}{{ item[1] }}"
  with_nested:
    - "{{ add_master_ip_list }}"
    - ['etcd-ca.pem', 'etcd.pem', 'etcd-key.pem', 'etcd-ca-key.pem']