---
- name: Create Docker Cert Config Dir
  file:
    path: "/etc/docker/certs.d"
    mode: 0777
    owner: "{{ ssh_connect_user }}"
    state: directory
  ignore_errors: true

## Create Docker Cert Dir
- name: Copy Client CA Files in All K8s Nodes
  shell: "sudo ssh -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -i {{ ssh_public_key }} \
            -p {{ ssh_connect_port }} {{ ssh_connect_user }}@{{ item[0] }} 'sudo mkdir -p /etc/docker/certs.d && sudo chown {{ ssh_connect_user }} /etc/docker/certs.d'"
  with_nested:
    - "{{ k8s_all_ip_list }}"
    - "-"
  ignore_errors: true

## Copy Client CA Files in All K8s Nodes
- name: Copy Client CA Files in All K8s Nodes
  shell: "sudo scp -r -p -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -i {{ ssh_public_key }} \
            -P {{ ssh_connect_port }} {{ kubernetes_etc_dirs }}harbor/cert/{{ item[1] }}  {{ ssh_connect_user }}@{{ item[0] }}:/etc/docker/certs.d"
  with_nested:
    - "{{ k8s_all_ip_list }}"
    - "{{ harbor_ingress_default_domain }}"
  ignore_errors: true