---

- name: Ubuntu Install JQ
  apt: 
    name: ["jq"]
    state: present
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  when: ansible_distribution == 'Ubuntu'
  async: 30
  poll: 2
  ignore_errors: true

- name: Centos Install JQ
  yum: 
    name: ["jq"]
    state: present
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  async: 30
  poll: 2
  when: ansible_distribution == 'CentOS'
  ignore_errors: true

- name: Delete Kubernetes Cluster Nodes
  shell: >
    export DELETE_NONE=`{{ kubernetes_ctl_path }}kubectl get node -o json | jq '.items[].status.addresses'| jq '{IP:.[0].address,HOSTNAME:.[1].address}' -c | jq '. | select(.IP | contains(\"{{ item[0] }}\"))' | jq --raw-output .HOSTNAME`
    {{ kubernetes_ctl_path }}kubectl cordon $DELETE_NONE
    {{ kubernetes_ctl_path }}kubectl drain $DELETE_NONE --force --ignore-daemonsets --delete-local-data
    sleep 12
    {{ kubernetes_ctl_path }}kubectl delete node $$DELETE_NONE
  with_nested:
    - "{{ k8s_del_node_ip_list }}"
    - "-"
  ignore_errors: true