---
- name: Remove System Containerd Configs
  shell: "mv {{ systemd_default_dirs }}containerd.service {{ temporary_dirs }}remove-cluster"
  ignore_errors: true

- name: Systemd Reload Remove Containerd
  shell: "systemctl daemon-reload"
  ignore_errors: true

- name: Remove Containerd Configs
  shell: "mv /etc/containerd {{ temporary_dirs }}remove-cluster"
  ignore_errors: true