## Kube TLS
## ********************************************************************************************************************************

# CFSSL 生成证书的加密方式
tls_k8s_encryption_algorithm: 'rsa'

# CFSSL 生成证书的通过加密算法生成的长度
tls_k8s_encryption_algorithm_size: 2048

# 证书有效期, 默认为 5 年, CA 根证书与 server 证书使用一个时间
tls_k8s_validity_period: 20

# 证书信息头, 国家信息 
# Country Name
tls_k8s_head_info_C: 'CN'

# 证书信息头, 地区或城市 
# Locality Name
tls_k8s_head_info_L: 'BeiJing'

# 证书信息头, 组织 
# Organization Name 
tls_k8s_head_info_O: 'Kubernetes'

# 证书信息头, 组织单位 
# Organizational Units Name
tls_k8s_head_info_OU: 'Kubernetes'

# 证书信息头, 州或省 
# State or Province Name
tls_k8s_head_info_ST: 'BeiJing'

## Deploy Kubernetes Cluster Host list
## ********************************************************************************************************************************

k8s_master_ip_list: >-
  [{% for host in groups['kube-master'] -%}
    '{{ hostvars[host].ansible_default_ipv4.address }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

k8s_master_name_list: >-
  [{% for host in groups['kube-master'] -%}
    '{{ hostvars[host].ansible_nodename }}'
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}]

k8s_master_ip_str: >-
  {% for host in groups['kube-master'] -%}
    {{ hostvars[host].ansible_default_ipv4.address }}
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}

all_hostname_str: >-
  {% for host in groups['kube-master'] -%}
    {{ hostvars[host]['ansible_nodename'] }}
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}

# TLS
## ********************************************************************************************************************************

admin_tls_k8s_head_info_O: 'system:masters'
nodes_tls_k8s_head_info_O: 'system:nodes'
controller_manager_tls_k8s_head_info_O: 'system:kube-controller-manager'
scheduler_tls_k8s_head_info_O: 'system:kube-scheduler'

tls_k8s_validity_period_hours: '{{ tls_k8s_validity_period * 365 * 24 }}'


