---
- name: Copy Etcd CA Files in Nodes
  shell: "sudo scp -r -p -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -i {{ ssh_public_key }} \
            -P {{ ssh_connect_port }} {{ etcd_ssl_dirs }}{{ item[1] }}  {{ ssh_connect_user }}@{{ item[0] }}:{{ etcd_ssl_dirs }}{{ item[1] }}"
  with_nested:
    - "{{ etcd_add_node_ip_list }}"
    - ['etcd-ca.pem', 'etcd-ca-key.pem']