---

# System
## ********************************************************************************************************************************

- name: Copy kubelet.service Files
  template: 
    src: kubelet.service.j2
    dest: "{{ systemd_default_dirs }}kubelet.service"
    mode: 0644
    owner: "{{ ssh_connect_user }}"

- name: Copy 10-kubelet.conf Files
  template: 
    src: 10-kubelet.j2
    dest: "{{ systemd_etc_dirs }}kubelet.service.d/10-kubelet.conf"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
    
- name: Copy Kubelet Config
  template: 
    src: "config.j2"
    dest: "{{ kubelet_work_dirs }}config.yaml"
    mode: 0644
    owner: "{{ ssh_connect_user }}"

- name: Copy Kubelet Env Config
  template: 
    src: "kubernetes-flags.j2"
    dest: "{{ kubelet_work_dirs }}kubernetes-flags.env"
    mode: 0644
    owner: "{{ ssh_connect_user }}"

# - name: Create Kubelet PEM
#   include_tasks: includes/kubelet_pem.yml
  
- include_tasks: 'roles/kubernetes-default/includes/start-kubelet.yaml'