---
- include_vars: "roles/cri-install/vars/containerd.yaml"

- name: Clean Containerd Services
  include: "roles/clean-install/includes/containerd/services.yaml"

- name: Containerd Turn off Start Up
  service: 
    name: "{{ item }}"
    enabled: no
  with_items:
    - "containerd"
  ignore_errors: true
  
- name: Stop Containerd.
  service:
    name: "containerd"
    state: stopped
  ignore_errors: true
  
# Clean Containerd Socket
- name: Clean Containerd Socket
  shell: "rm -rf {{ containerd_socket_path }}"
  ignore_errors: true

- name: Umount Containerd Drive
  shell: "for i in `cat /proc/mounts | grep '{{ containerd_run_path }}' | awk '{print $2}'`;do umount -l $i; done"
  ignore_errors: true

- name: Clean Containerd Shim Services
  include: "roles/clean-install/includes/containerd/shim.yaml"

# Clean Containerd Image
# - name: Clean Containerd Image
#   include: "roles/clean-install/includes/containerd/image.yaml"
#   when: is_remove_all or is_remove_k8s_images

- name: Clean Containerd Config
  include: "roles/clean-install/includes/containerd/config.yaml"
  when: is_remove_all or is_remove_containerd

- name: Clean Containerd Binary
  include: "roles/clean-install/includes/containerd/binary.yaml"
  when: is_remove_all or is_remove_containerd

- name: Clean Containerd Data
  include: "roles/clean-install/includes/containerd/data.yaml"
  when: is_remove_all or is_remove_containerd_dir

