---
## Copy Kubernetes Certification Files in Nodes
- name: Copy Kubernetes Certification Files in Nodes
  shell: "sudo scp -r -p -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -i {{ ssh_public_key }} \
            -P {{ ssh_connect_port }} {{ kubernetes_etc_dirs }}{{ item[1] }}  {{ ssh_connect_user }}@{{ item[0] }}:{{ kubernetes_etc_dirs }}{{ item[1] }}"
  with_nested:
    - "{{ k8s_node_ip_list }}"
    - ['pki/ca.pem', 'pki/ca-key.pem', 'bootstrap-kubelet.conf']

## Copy Etcd CA Files in Nodes
# - name: Copy Etcd CA Files in Nodes
#   shell: "sudo scp -r -p -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -i {{ ssh_public_key }} \
#             -P {{ ssh_connect_port }} {{ etcd_ssl_dirs }}{{ item[1] }}  {{ ssh_connect_user }}@{{ item[0] }}:{{ etcd_ssl_dirs }}{{ item[1] }}"
#   with_nested:
#     - "{{ k8s_node_ip_list }}"
#     - ['etcd-ca.pem', 'etcd.pem', 'etcd-key.pem']