---
- name: Ubuntu Install Containerd roles
  include: roles/cri-install/includes/containerd/ubuntu.yaml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Centos Install Containerd roles
  include: roles/cri-install/includes/containerd/centos.yaml
  when: ansible_distribution == 'CentOS'