---
## Copy Kubernetes Manifests Files
## ********************************************************************************************************************************
- name: Create Kubernetes PKI WorkDir
  file:
    path: "{{ kubernetes_manifests_dirs }}"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory
  when: is_kube_master or is_add_master

- name: Copy Kubernetes ApiServer Config Files
  template: 
    src: kube-apiserver.j2
    dest: "{{ kubernetes_manifests_dirs }}kube-apiserver.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}" 
  when: is_kube_master or is_add_master

- name: Copy Kubernetes Controller Manager Config Files
  template: 
    src: kube-controller-manager.j2
    dest: "{{ kubernetes_manifests_dirs }}kube-controller-manager.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}" 
  when: is_kube_master or is_add_master

- name: Copy Kubernetes Scheduler Config Files
  template: 
    src: kube-scheduler.j2
    dest: "{{ kubernetes_manifests_dirs }}kube-scheduler.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}" 
  when: is_kube_master or is_add_master

- name: Copy encryption Config Files
  copy: 
    src: master/encryption.yml
    dest: "{{ kubernetes_etc_dirs }}encryption.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}" 
  when: is_kube_master or is_add_master

- name: Copy audit-policy Config Files
  copy: 
    src: master/audit-policy.yml
    dest: "{{ kubernetes_etc_dirs }}audit-policy.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}" 
  when: is_kube_master or is_add_master

# Haproxy
## ********************************************************************************************************************************

- name: Create Haproxy WorkDir
  file:
    path: "{{ haproxy_etc_dirs }}"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory
  when: is_kube_master or is_add_master

- name: Copy Haproxy cfg Files
  template: 
    src: haproxy.cfg.j2
    dest: "{{ haproxy_etc_dirs }}haproxy.cfg"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
  when: is_kube_master or is_add_master

- name: Copy Haproxy conf Files
  template: 
    src: haproxy.yml.j2
    dest: "{{ kubernetes_manifests_dirs }}haproxy.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
  when: is_kube_master or is_add_master


# Keepalived
## ********************************************************************************************************************************

- name: Copy keepalived config Files
  template: 
    src: keepalived.j2
    dest: "{{ kubernetes_manifests_dirs }}keepalived.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}"
  when: (is_keepalived and is_kube_master) or (is_keepalived and is_add_master)
