---

- name: Create Crane Temporary Directory
  file:
    path: "{{ temporary_dirs }}"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory

- name: Backup Old Crane Tasks Temporary Directory
  shell: "mv {{ temporary_dirs }} {{ temporary_dirs }}{{ crane_tasks }}-`date +%Y%m%d%H%M%S`"
  ignore_errors: true

- name: Create Crane Tasks Temporary Directory
  file:
    path: "{{ temporary_dirs }}{{ crane_tasks }}"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory

- name: Create Crane Private Directory
  file:
    path: "/etc/crane"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory