---
- name: Clean Istio Directory
  file:
    path: "{{ istio_home }}"
    state: absent
  ignore_errors: true

- name: Create Istio Directory
  file:
    path: "{{ istio_home }}"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory

- name: Deploy Istio *
  shell: "cd {{ istio_home }} && curl -x '{{ http_proxy }}' -sL https://git.io/getLatestIstio | ISTIO_VERSION={{ istio_version }} ALL_PROXY='{{ http_proxy }}' sh -" 

- name: Deploy Istio **
  shell: 'cd {{ istio_home }} && until {{ kubernetes_ctl_path }}kubectl apply -f install/kubernetes/ ; do >&2 echo "Starting..." && sleep 1 ; done'

- name: Deploy Istio ***
  template: 
    src: roles/add-ons/templates/istio/ingress.yml
    dest: "{{ istio_home }}istio-ingress.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}" 

- name: Deploy Istio ****
  shell: 'until {{ kubernetes_ctl_path }}kubectl apply -f {{ istio_home }}istio-ingress.yml ; do >&2 echo "Starting..." && sleep 1 ; done'

- name: Deploy Istio *****
  template: 
    src: roles/add-ons/templates/istio/kiali-secret.yml
    dest: "{{ istio_home }}kiali-secret.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}" 

- name: Deploy Istio ******
  shell: 'until {{ kubernetes_ctl_path }}kubectl apply -f {{ istio_home }}kiali-secret.yml ; do >&2 echo "Starting..." && sleep 1 ; done'

- name: Deploy Istio *******
  shell: 'ln -sf {{ istio_home }}/bin/istioctl /usr/bin/istioctl'