---
- include_vars: "roles/cri-install/vars/crio.yaml"

- name: CRIO Turn off Start Up
  service: 
    name: "{{ item }}"
    enabled: no
  with_items:
    - "crio"
  ignore_errors: true

- name: Stop CRIO.
  service:
    name: "crio"
    state: stopped
  ignore_errors: true

# Clean CRIO Socket
- name: Clean CRIO Socket
  shell: "rm -rf {{ crio_socket_path }}"
  ignore_errors: true

- name: Umount CRIO Drive
  shell: "for i in `cat /proc/mounts | grep '{{ crio_data_root }}' | awk '{print $2}'`;do umount $i; done"
  ignore_errors: true

- name: Umount CRIO Run Drive >
  shell: "for i in `cat /proc/mounts | grep '{{ crio_run_data_root }}' | awk '{print $2}'`;do umount $i; done"
  ignore_errors: true

- name: Umount CRIO Run Drive >>
  shell: "for i in `cat /proc/mounts | grep '/run/containers/storage' | awk '{print $2}'`;do umount $i; done"
  ignore_errors: true
  
- name: Clean CRIO Binary Files
  file:
    path: "{{ kubernetes_ctl_path }}{{ item }}"
    state: absent
  with_items:
    - "conmon"
    - "crictl"
    - "crio"
    - "crio-status"
    - "crun"
    - "pinns"
  ignore_errors: true
  when: is_remove_all or is_remove_crio

- name: Remove System CRIO Configs
  shell: "mv {{ systemd_default_dirs }}crio.service {{ temporary_dirs }}clean-cluster"
  when: is_remove_all or is_remove_crio
  ignore_errors: true

- name: Systemd Reload Remove Containerd
  shell: "systemctl daemon-reload"
  ignore_errors: true

- name: Remove CRIO Configs
  shell: "mv /etc/crio {{ temporary_dirs }}clean-cluster"
  when: is_remove_all or is_remove_crio
  ignore_errors: true

- name: Remove CRIO Env Configs
  shell: "mv /etc/default/crio {{ temporary_dirs }}clean-cluster"
  when: is_remove_all or is_remove_crio
  ignore_errors: true

- name: Remove CRIO Ctrctl Configs
  shell: "mv /etc/crictl.yaml {{ temporary_dirs }}clean-cluster"
  when: is_remove_all or is_remove_containerd
  ignore_errors: true

- name: Remove CRIO Data Path
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ crio_run_data_root }}"
    - "{{ crio_data }}"
    - "/var/log/crio/pods"
    - "/var/run/crio/version"
    - "/var/run/crio/crio.sock"
    - "/var/lib/crio"
    - "/etc/containers"
  ignore_errors: true
  when: is_remove_all or is_remove_crio_dir

