## All Clear
## ********************************************************************************************************************************
# 此选项会忽略下面所有配置项
# 主要目的是恢复安装 Crane 涉及到所有组件之前的状况
# 如果此值为 false 它会清除 k8s Cluster 绝大部分数据, 方便下一次部署时避免重复安装如 kubelet、docker 等
is_remove_all: false


## CRI-Tools
## ********************************************************************************************************************************

# 清除集群时是否删除 CRICRL.
is_remove_crictl: false


## Docker
## ********************************************************************************************************************************

# 清除集群时是否删除 Docker.
is_remove_docker_ce: false

# 清除集群时是否删除不是基于 Crane 安装的 Docker.
is_remove_not_crane_docker_ce: false

# 清除 Docker CE 时清除数据目录.
is_remove_docker_dir: false

# 清除 Docker Configs 文件
is_remove_docker_daemon_cfg: false

# 清除 Docker 时 是否清除附带的 Containerd
is_remove_docker_containerd: "{{ is_remove_docker_ce }}"


## CRIO
## ********************************************************************************************************************************

# 清除集群时是否删除 CRIO.
is_remove_crio: false

# 是否清除 CRIO 数据目录
is_remove_crio_dir: false


## Containerd
## ********************************************************************************************************************************

# 清除集群时是否删除 Containerd.
is_remove_containerd: false

# 是否清除 Containerd 数据目录
is_remove_containerd_dir: false

# 清除集群时是否删除不是基于 Crane 安装的 Containerd.
is_remove_not_crane_containerd: false

## runC
## ********************************************************************************************************************************

# 清除集群时是否删除 runC.
is_remove_runc: false

## CNI
## ********************************************************************************************************************************
# 清除集群时是否删除 CNI 插件.
is_remove_cni: false


## Kubernetes
## ********************************************************************************************************************************

# 是否清除 Kubelet Kubectl 可执行文件.
is_remove_k8s_binary: false

# 是否清除 Kubernetes Images.
is_remove_k8s_images: false


## Iptables
## ********************************************************************************************************************************

# 是否清除集群时清除 iptables 规则，如果有自己定义的规则，建议关闭此选项，但在清除之前会进行保存
is_remove_iptables_rule: false


## Etcd
## ********************************************************************************************************************************

# 是否清除 etcd
is_remove_etcd: true


## Other
## ********************************************************************************************************************************

# 清除集群时是否删除 CFSSL 可执行文件.
is_remove_cfssl: false

# 是否关闭 Swap, 当值为 false 时, 则表示不作任何操作, 当为 true 时, 会关闭服务器上所有的 Swap.
is_swap_off: false

# 是否清除临时存放目录
is_remove_temporary: false

