---
# Kubernetes
## ********************************************************************************************************************************
- name: Check Kubernetes Package
  shell: "ls {{ temporary_dirs }}kubernetes/node/bin"
  register: CHECK_KUBE_BIN_PACKAGE
  ignore_errors: true

- name: Download Kubernetes Ctl And Kubelet Binary Files
  shell: "http_proxy={{ http_proxy }} ; https_proxy={{ https_proxy }} ; wget -qO- 'https://dl.k8s.io/{{ k8s_version }}/kubernetes-node-linux-amd64.tar.gz' | tar zx -C {{ temporary_dirs }}"
  changed_when: true
  when: CHECK_KUBE_BIN_PACKAGE is failed

- name: Copy Kubectl
  shell: "cp -rf {{ temporary_dirs }}kubernetes/node/bin/kubectl {{ kubernetes_ctl_path }}"

- name: Copy Kubelet
  shell: "cp -rf {{ temporary_dirs }}kubernetes/node/bin/kubelet {{ kubernetes_ctl_path }}"

- name: Check CNI Dir
  shell: "ls {{ kubernetes_cni_dirs }}"
  register: CHECK_CNI_BIN_PACKAGE
  ignore_errors: true

- name: Download Kubernetes-cni Plugin Binary Files
  file:
    path: "{{ kubernetes_cni_dirs }}"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory
  when: CHECK_CNI_BIN_PACKAGE is failed

- name: Download CNI Package
  shell: "http_proxy={{ http_proxy }} ; https_proxy={{ https_proxy }} ; wget -qO- 'https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-{{ cni_os_drive }}-{{ cni_version }}.tgz' | tar -zx -C {{ kubernetes_cni_dirs }}"
  when: CHECK_CNI_BIN_PACKAGE is failed
  
# CFSSL
## ********************************************************************************************************************************
- name: Download CFSSL Binary Files *
  shell: "curl -x '{{ http_proxy }}' -s -o {{ kubernetes_ctl_path }}cfssl https://pkg.cfssl.org/R1.2/cfssl_linux-amd64"

- name: Download CFSSL Binary Files **
  shell: "curl -x '{{ http_proxy }}' -s -o {{ kubernetes_ctl_path }}cfssljson https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64"

- name: Download CFSSL Binary Files ***
  shell: "chmod +x {{ kubernetes_ctl_path }}cfssl*"
